### ISSUE TITLE
Compiler error: qwebengineview.h: No such file or directory

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/Qkinz#16]
I get an error when trying to compile Qkinz 477ca9c2123c45dd4f0e7ccd65ec4e6be9d31ccb wike qmake and make:
```
 In file included from gui/src/mainwindow.cpp:2:0:
../build/src/ui/ui_mainwindow.h:35:28: fatal error: qwebengineview.h: No such file or directory
```

System:
Linux Mint 18.3, build with 
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu

**Comment by fzeiser** [comment]
Seems to be a problem related to the QT version, see:
https://forum.qt.io/topic/65398/qwebengineview-in-qtdesigner

I think the change was introduced in fa66cec38c352771f50e7bfe6d8643ac0a728610

**Comment by fzeiser** [comment]
I changed to qmake with qt5.5.1

```console  --mdpopups-admon-error-fg
fabiobz@fabiobz:~$ qmake Qkinz.pro 
fabiobz@fabiobz:~$ make
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/fabiobz/.local/share/Trash/files/Qkinz-1.3.3/src/src.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/fabiobz/.local/share/Trash/files/Qkinz-1.3.3/src'
/usr/lib/x86_64-linux-gnu/qt4/bin/uic gui/forms/mainwindow.ui -o ../build/src/ui/ui_mainwindow.h
/usr/lib/x86_64-linux-gnu/qt4/bin/uic gui/forms/selectbeamform.ui -o ../build/src/ui/ui_selectbeamform.h
/usr/lib/x86_64-linux-gnu/qt4/bin/uic gui/forms/selecttargetform.ui -o ../build/src/ui/ui_selecttargetform.h
/usr/lib/x86_64-linux-gnu/qt4/bin/uic gui/forms/selecttelescopeform.ui -o ../build/src/ui/ui_selecttelescopeform.h
/usr/lib/x86_64-linux-gnu/qt4/bin/uic gui/forms/rundialog.ui -o ../build/src/ui/ui_rundialog.h
/usr/lib/x86_64-linux-gnu/qt4/bin/uic gui/forms/selectfrontbackform.ui -o ../build/src/ui/ui_selectfrontbackform.h
g++ -c -m64 -pipe -std=c++11 -O2 -fPIC -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -Igui/include -Ikinematics/include -Imath/include -Imatter/include -Isupport/include -Itables/include -I../build/src/moc -I../build/src/ui -o ../build/src/objects/mainwindow.o gui/src/mainwindow.cpp
In file included from /usr/include/qt4/QtCore/QThread:1:0,
                 from gui/include/mainwindow.h:5,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qthread.h: In constructor ‘MainWindow::MainWindow(QWidget*)’:
/usr/include/qt4/QtCore/qthread.h:106:10: error: ‘void QThread::finished()’ is protected
     void finished();
          ^
gui/src/mainwindow.cpp:48:36: error: within this context
     connect(&workThread, &QThread::finished, worker, &QObject::deleteLater);
                                    ^
gui/src/mainwindow.cpp:48:75: error: no matching function for call to ‘MainWindow::connect(QThread*, void (QThread::*)(), Worker*&, void (QObject::*)())’
     connect(&workThread, &QThread::finished, worker, &QObject::deleteLater);
                                                                           ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmainwindow.h:45,
                 from /usr/include/qt4/QtGui/QMainWindow:1,
                 from gui/include/mainwindow.h:4,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (QThread::*)()’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (QThread::*)()’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (QThread::*)()’ to ‘const char*’
gui/src/mainwindow.cpp:49:61: error: no matching function for call to ‘MainWindow::connect(MainWindow*, void (MainWindow::*)(const double&, const bool&, const bool&, const bool&, const bool&, const bool&), Worker*&, void (Worker::*)(const double&, const bool&, const bool&, const bool&, const bool&, const bool&))’
     connect(this, &MainWindow::operate, worker, &Worker::Run);
                                                             ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmainwindow.h:45,
                 from /usr/include/qt4/QtGui/QMainWindow:1,
                 from gui/include/mainwindow.h:4,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (MainWindow::*)(const double&, const bool&, const bool&, const bool&, const bool&, const bool&)’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (MainWindow::*)(const double&, const bool&, const bool&, const bool&, const bool&, const bool&)’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (MainWindow::*)(const double&, const bool&, const bool&, const bool&, const bool&, const bool&)’ to ‘const char*’
In file included from gui/include/mainwindow.h:16:0,
                 from gui/src/mainwindow.cpp:1:
support/include/worker.h:45:10: error: ‘void Worker::ResultCurve(const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&)’ is protected
     void ResultCurve(const QVector<double> &x,      /*!< The x-value result.   
          ^
gui/src/mainwindow.cpp:50:30: error: within this context
     connect(worker, &Worker::ResultCurve, this, &MainWindow::CurveData);
                              ^
gui/src/mainwindow.cpp:50:71: error: no matching function for call to ‘MainWindow::connect(Worker*&, void (Worker::*)(const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&), MainWindow*, void (MainWindow::*)(const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&))’
     connect(worker, &Worker::ResultCurve, this, &MainWindow::CurveData);
                                                                       ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmainwindow.h:45,
                 from /usr/include/qt4/QtGui/QMainWindow:1,
                 from gui/include/mainwindow.h:4,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (Worker::*)(const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&)’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (Worker::*)(const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&)’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (Worker::*)(const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&)’ to ‘const char*’
In file included from gui/include/mainwindow.h:16:0,
                 from gui/src/mainwindow.cpp:1:
support/include/worker.h:51:10: error: ‘void Worker::ResultScatter(const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&)’ is protected
     void ResultScatter(const QVector<double> &x,    /*!< The x-value result.   
          ^
gui/src/mainwindow.cpp:51:30: error: within this context
     connect(worker, &Worker::ResultScatter, this, &MainWindow::ScatterData);
                              ^
gui/src/mainwindow.cpp:51:75: error: no matching function for call to ‘MainWindow::connect(Worker*&, void (Worker::*)(const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&), MainWindow*, void (MainWindow::*)(const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&))’
     connect(worker, &Worker::ResultScatter, this, &MainWindow::ScatterData);
                                                                           ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmainwindow.h:45,
                 from /usr/include/qt4/QtGui/QMainWindow:1,
                 from gui/include/mainwindow.h:4,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (Worker::*)(const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&)’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (Worker::*)(const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&)’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (Worker::*)(const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const QVector<double>&, const Fragment_t&)’ to ‘const char*’
In file included from gui/include/mainwindow.h:16:0,
                 from gui/src/mainwindow.cpp:1:
support/include/worker.h:59:10: error: ‘void Worker::FinishedAll()’ is protected
     void FinishedAll();
          ^
gui/src/mainwindow.cpp:52:30: error: within this context
     connect(worker, &Worker::FinishedAll, this, &MainWindow::WorkFinished);
                              ^
gui/src/mainwindow.cpp:52:74: error: no matching function for call to ‘MainWindow::connect(Worker*&, void (Worker::*)(), MainWindow*, void (MainWindow::*)())’
     connect(worker, &Worker::FinishedAll, this, &MainWindow::WorkFinished);
                                                                          ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmainwindow.h:45,
                 from /usr/include/qt4/QtGui/QMainWindow:1,
                 from gui/include/mainwindow.h:4,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (Worker::*)()’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (Worker::*)()’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (Worker::*)()’ to ‘const char*’
In file included from gui/include/mainwindow.h:16:0,
                 from gui/src/mainwindow.cpp:1:
support/include/worker.h:61:10: error: ‘void Worker::curr_prog(double)’ is protected
     void curr_prog(double);
          ^
gui/src/mainwindow.cpp:53:30: error: within this context
     connect(worker, &Worker::curr_prog, runDialog, &RunDialog::progress);
                              ^
gui/src/mainwindow.cpp:53:72: error: no matching function for call to ‘MainWindow::connect(Worker*&, void (Worker::*)(double), RunDialog*&, void (RunDialog::*)(double))’
     connect(worker, &Worker::curr_prog, runDialog, &RunDialog::progress);
                                                                        ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmainwindow.h:45,
                 from /usr/include/qt4/QtGui/QMainWindow:1,
                 from gui/include/mainwindow.h:4,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (Worker::*)(double)’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (Worker::*)(double)’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (Worker::*)(double)’ to ‘const char*’
In file included from /usr/include/qt4/QtCore/QThread:1:0,
                 from gui/include/mainwindow.h:5,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qthread.h:106:10: error: ‘void QThread::finished()’ is protected
     void finished();
          ^
gui/src/mainwindow.cpp:57:37: error: within this context
     connect(&batchThread, &QThread::finished, bReader, &QObject::deleteLater);
                                     ^
gui/src/mainwindow.cpp:57:77: error: no matching function for call to ‘MainWindow::connect(QThread*, void (QThread::*)(), BatchReader*&, void (QObject::*)())’
     connect(&batchThread, &QThread::finished, bReader, &QObject::deleteLater);
                                                                             ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmainwindow.h:45,
                 from /usr/include/qt4/QtGui/QMainWindow:1,
                 from gui/include/mainwindow.h:4,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (QThread::*)()’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (QThread::*)()’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (QThread::*)()’ to ‘const char*’
gui/src/mainwindow.cpp:58:74: error: no matching function for call to ‘MainWindow::connect(MainWindow*, void (MainWindow::*)(QString), BatchReader*&, void (BatchReader::*)(const QString&))’
     connect(this, &MainWindow::runBatchFile, bReader, &BatchReader::Start);
                                                                          ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmainwindow.h:45,
                 from /usr/include/qt4/QtGui/QMainWindow:1,
                 from gui/include/mainwindow.h:4,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (MainWindow::*)(QString)’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (MainWindow::*)(QString)’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (MainWindow::*)(QString)’ to ‘const char*’
In file included from gui/include/mainwindow.h:17:0,
                 from gui/src/mainwindow.cpp:1:
support/include/BatchReader.h:24:10: error: ‘void BatchReader::FinishedAll()’ is protected
     void FinishedAll();
          ^
gui/src/mainwindow.cpp:59:36: error: within this context
     connect(bReader, &BatchReader::FinishedAll, this, &MainWindow::finishBFile)
                                    ^
gui/src/mainwindow.cpp:59:79: error: no matching function for call to ‘MainWindow::connect(BatchReader*&, void (BatchReader::*)(), MainWindow*, void (MainWindow::*)())’
    connect(bReader, &BatchReader::FinishedAll, this, &MainWindow::finishBFile);
                                                                              ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmainwindow.h:45,
                 from /usr/include/qt4/QtGui/QMainWindow:1,
                 from gui/include/mainwindow.h:4,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (BatchReader::*)()’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (BatchReader::*)()’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (BatchReader::*)()’ to ‘const char*’
In file included from gui/include/mainwindow.h:17:0,
                 from gui/src/mainwindow.cpp:1:
support/include/BatchReader.h:25:10: error: ‘void BatchReader::curr_prog(double)’ is protected
     void curr_prog(double);
          ^
gui/src/mainwindow.cpp:60:36: error: within this context
     connect(bReader, &BatchReader::curr_prog, runDialog, &RunDialog::progress);
                                    ^
gui/src/mainwindow.cpp:60:78: error: no matching function for call to ‘MainWindow::connect(BatchReader*&, void (BatchReader::*)(double), RunDialog*&, void (RunDialog::*)(double))’
     connect(bReader, &BatchReader::curr_prog, runDialog, &RunDialog::progress);
                                                                              ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47:0,
                 from /usr/include/qt4/QtGui/qmainwindow.h:45,
                 from /usr/include/qt4/QtGui/QMainWindow:1,
                 from gui/include/mainwindow.h:4,
                 from gui/src/mainwindow.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (BatchReader::*)(double)’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (BatchReader::*)(double)’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (BatchReader::*)(double)’ to ‘const char*’
In file included from gui/include/mainwindow.h:13:0,
                 from gui/src/mainwindow.cpp:1:
gui/include/rundialog.h: In member function ‘void MainWindow::WorkFinished()’:
gui/include/rundialog.h:41:10: error: ‘void RunDialog::Finished()’ is protected
     void Finished();
          ^
gui/src/mainwindow.cpp:375:30: error: within this context
     emit runDialog->Finished();
                              ^
gui/src/mainwindow.cpp: In member function ‘void MainWindow::on_actionExport_table_triggered()’:
gui/src/mainwindow.cpp:471:30: error: ‘class QWebPage’ has no member named ‘printToPdf’
         ui->webView->page()->printToPdf(FilePath);
                              ^
gui/src/mainwindow.cpp: In member function ‘void MainWindow::on_actionAbout_Qt_triggered()’:
gui/src/mainwindow.cpp:532:5: error: ‘QMessageBox’ has not been declared
     QMessageBox::aboutQt(this);
     ^
gui/src/mainwindow.cpp: In member function ‘void MainWindow::on_actionAbout_triggered()’:
gui/src/mainwindow.cpp:542:5: error: ‘QMessageBox’ has not been declared
     QMessageBox::about(this, tr("About Qkinz"), ts.readAll());
     ^
gui/src/mainwindow.cpp: In member function ‘void MainWindow::on_actionAbout_QCustomPlot_triggered()’:
gui/src/mainwindow.cpp:553:5: error: ‘QMessageBox’ has not been declared
     QMessageBox::about(this, tr("About QCustomPlot 1.30"), ts.readAll());
     ^
gui/src/mainwindow.cpp: In member function ‘void MainWindow::on_actionOpen_triggered()’:
gui/src/mainwindow.cpp:520:51: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
         fread(&theBeam, sizeof(Beam_t), 1, inFile);
                                                   ^
gui/src/mainwindow.cpp:521:55: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
         fread(&theTarget, sizeof(Target_t), 1, inFile);
                                                       ^
gui/src/mainwindow.cpp:522:61: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
         fread(&theTelescope, sizeof(Telescope_t), 1, inFile);
                                                             ^
Makefile:472: recipe for target '../build/src/objects/mainwindow.o' failed
make[1]: *** [../build/src/objects/mainwindow.o] Error 1
make[1]: Leaving directory '/home/fabiobz/.local/share/Trash/files/Qkinz-1.3.3/src'
Makefile:44: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
```

**Comment by fzeiser** [comment]
Looking at the output I see that there is still a lot of includes fom qt4 - so it might be that I didn't change it propperly, eventhough the make file also says that it's created with qt5.5.1

**Comment by fzeiser** [comment]
Not sure what I changed, but now I get following error message. Shall try to see what happens after a restart:
``` console
fabiobz@fabiobz:~$ qmake Qkinz.pro 
fabiobz@fabiobz:~$ make
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/fabiobz/Downloads/Qkinz-1.3.3/src/src.pro -o Makefile ) && make -f Makefile 
Project ERROR: Unknown module(s) in QT: webenginewidgets
Makefile:44: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 3
```

The error appears eventhough I installed `libqt5webkit5-dev`

**Comment by fzeiser** [comment]
Still having the same troubles with the `webenginewidgets` module, so I can't compile.

**Comment by fzeiser** [comment]
It seems like I'm missing the `webenginewidgets`, which wasn't installed from the standard repo following qt 5.5.1 with ubuntu 16. There it's still webkit.

Instructions on how to install:
http://wiki.qt.io/QtWebEngine/How_to_Try#Get_the_code

Didn't work for me though. It might be easiest installing >=qt5.10 so something like this directly and then build qkinz from there.

**Comment by fzeiser** [comment]
Confirmed the last idea. Tried `qt-5.11.2` and it worked.
